map/urls.py
from django.urls import path
from . import views
app_name = "map"

urlpatterns=[
    path('direction/',views.direction,name='direction'),
]

meds_nearby/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from search import views as search_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('',search_views.get_coord_api,name='get_coord'),
    path('map/',include('map.urls')),
    path('user/',include('users.urls')),

    #path('login/',auth_views.LoginView.as_view(template_name='user_registration/login.html'),name='login'),
    #path('logout/',auth_views.LogoutView.as_view(template_name='user_registration/logout.html'),name='logout')'''
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = "users"
urlpatterns=[
    path('register/',views.register,name='register'),
    path('profile/',views.profile_pg,name='profile'),
    path('login/',views.custom_login,name='login'),
    path('logout/',views.custom_logout,name='logout'),
    path('edit-profile/',views.edit_profile,name='edit'),
    path('request_order/<str:med_name>/<str:pharma_email>/<str:pharma_name>/',views.request_order,name='request_order'),
    path('activate/<uidb64>/<token>',views.activate, name='activate'),
    ]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms 
medicines=[('','search'),
           ('Lobate Cream', 'Lobate Cream'), 
           ('Liv 52 DS Tablet', 'Liv 52 DS Tablet'), 
           ('Morr F 5% Solution', 'Morr F 5% Solution'), 
           ('Omez FF 40mg Tablet', 'Omez FF 40mg Tablet'), 
           ('Parit 20mg Tablet', 'Parit 20mg Tablet'), 
           ('Progynova 1mg Tablet', 'Progynova 1mg Tablet'), 
           ('Prosure Powder', 'Prosure Powder'), 
           ('Urispas 200mg Tablet', 'Urispas 200mg Tablet'), 
           ('Qilib Men Lotion', 'Qilib Men Lotion'), 
           ('Paragis D 20mg/650mg Tablet', 'Paragis D 20mg/650mg Tablet'), 
           ('Quadriderm NF Cream', 'Quadriderm NF Cream'), 
           ('Seretide Evohaler 50mcg/100mcg Inhaler', 'Seretide Evohaler 50mcg/100mcg Inhaler'), 
           ('Sirdalud 2mg Tablet', 'Sirdalud 2mg Tablet'), 
           ('Stablon 12.5mg Tablet', 'Stablon 12.5mg Tablet'), 
           ('Stugeron 25mg Tablet', 'Stugeron 25mg Tablet'), 
           ('Swich O Tablet', 'Swich O Tablet'), 
           ('Synaptol 100mg Tablet', 'Synaptol 100mg Tablet'), 
           ('Telma ACT Tablet 40mg/5mg/12.5mg', 'Telma ACT Tablet 40mg/5mg/12.5mg'), 
           ('Tfil 10mg Tablet', 'Tfil 10mg Tablet'), 
           ('Trajenta 5mg Tablet', 'Trajenta 5mg Tablet')]
sort_=[('d','distance'),('p','price')]
class SearchForm(forms.Form):
    medicine=forms.ChoiceField(choices=medicines)
    postal_code=forms.CharField()
    search_radius_in_meter=forms.CharField(initial='4000')
    sortby=forms.ChoiceField(choices=sort_)

class CoordForm(forms.Form):
    to_lat=forms.CharField(widget=forms.HiddenInput)
    to_lon=forms.CharField(widget=forms.HiddenInput)
    frm_lat=forms.CharField(widget=forms.HiddenInput)
    frm_lon=forms.CharField(widget=forms.HiddenInput)

search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
import requests
import json

from .forms import SearchForm,CoordForm
# Create your views here.
def sort_by_distance(result):
    length=len(result)
    i=0
    while i<length:
        pharma=result[i]
        j=i-1
        while j>=0:
            if result[j]['distance']>pharma['distance']:
                temp=result[j]
                result[j]=pharma
                result[j+1]=temp
            j-=1
        i+=1
    '''print('in sbd',result)'''
    return result
    '''template='api_handling/result.html'
    data={'form':form,'result':result}
    return render(request,template,data)'''

def sort_By_price(result):
    length=len(result)
    i=0
    while i<length:
        pharma=result[i]
        j=i-1
        while j>=0:
            if result[j]['price']>pharma['price']:
                temp=result[j]
                result[j]=pharma
                result[j+1]=temp
            j-=1
        i+=1
    '''print(result)'''
    return result
def get_result(pharmacies,medicine_name):
    '''print('get_result')'''
    place_id=dict()
    i=0
    for pharma in pharmacies:
        place_id[i]=pharma['place_id']
        i+=1
    place_id=json.dumps(place_id)
    api=f"http://127.0.0.1:8000/api/pharmacies/?pharmacy_id={place_id}&medicine_name={medicine_name}"
    res=requests.get(api)
    result=json.loads(res.json())
    for result_pharma in result:
        for pharma in pharmacies:
            if result_pharma['place_id']==pharma['place_id']:
                result_pharma['distance']=pharma['distance']
                result_pharma['lat']=pharma['lat']
                result_pharma['lon']=pharma['lon']
    return result

def get_pharmacies(lon,lat,medicine_name,radius):
    '''print('get_phar')'''
    api=f'https://api.geoapify.com/v2/places?bias=proximity:{lon},{lat}&categories=healthcare.pharmacy&filter=circle:76.9843304,11.0629428,{radius}&limit=50&apiKey=d0f637b5187e487196dd3d9504742ecf'
    res=requests.get(api)
    dict_res=res.json()
    '''print('type',type(dict_res))'''
    features=dict_res['features']
    '''print('type feat',type(features),'\nfeatures len\n',len(features))'''
    pharmacy_details=[]
    for places in features:
        properties =places['properties']
        if 'name' in properties.keys():
            pharmacy_details.append({'name':properties['name'],'distance':properties['distance'],'place_id':properties['place_id'],'lat':properties['lat'],'lon':properties['lon']})
    '''print('phar len',len(pharmacy_details))
    print('details')'''
    '''for pharma in pharmacy_details:
        print(pharma['name'],pharma['distance'],pharma['place_id'],pharma['lat'],pharma['lon'])'''
    result=get_result(pharmacy_details,medicine_name)
    return result
def get_coord_api(request):
    if request.method=='GET':
        form=SearchForm()
        template='search/search.html'
        data={'form':form,'result':None}
        return render(request,template,data)
    if request.method=='POST':
        '''print(request.POST)'''
        form=SearchForm(request.POST)
        medicine_name=request.POST['medicine']
        radius=request.POST['search_radius_in_meter']
        sort_by=request.POST['sortby']
        api='https://api.geoapify.com/v1/geocode/search?postcode={}&format=json&apiKey=d0f637b5187e487196dd3d9504742ecf'.format(request.POST['postal_code'])
        res=requests.get(api)
        dict_res=res.json()
        lat=dict_res['results'][0]['lat']
        lon=dict_res['results'][0]['lon']
        '''print(lat,lon)'''
        result=get_pharmacies(lon,lat,medicine_name,radius)
        print('result:\n',result)
        if sort_by=='d':
            result=sort_by_distance(result)
        else:
            result=sort_By_price(result)
        print('r:\n',result)
        if len(result)==0:
            messages.warning(request,"Couldn't find any pharmacies in the specified radius that sell the searched medicine! please try increasing the search radius!")
        template='search/search.html'
        for r in result:
            value_={'to_lat':r['lat'],'to_lon':r['lon'],'frm_lat':lat,'frm_lon':lon}
            r['coord']=CoordForm(value_)
            print('r',r['coord'].is_valid())
        data={'form':form,'result':result,'medicine_name':medicine_name}
        return render(request,template,data)
        

search/templates/search/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>Meds Nearby</title>
</head>
<body>
    <div class="container_">
        <div class="nav_container">
            
            <nav class="nav">


                {%if request.path != '/polls/'%}
                <div class="nav_ele"><a href="{%url 'get_coord'%}">Home</a></div>
                
                {%endif%}
                {%if user.is_authenticated %}
                <div class="nav_ele"><a href="{%url 'users:logout'%}">Logout</a></div>
                <div class="nav_ele"><a href="{%url 'users:profile'%}">Profile</a></div>
            
                {%else%}
                <div class="nav_ele"><a href="{%url 'users:register'%}">Register</a></div>
                <div class="nav_ele"><a href="{%url 'users:login'%}">Login</a></div>      
                {%endif%}
            
            </nav>
            
        </div>
        <div>
            {% include 'search/messages.html'%}
        <div>
        <div class="container_main">
            

                <div>
                    {% block content %}
                    {%endblock content%}
                </div>
            </div>
            </div>
        </div>
        
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

search/templates/search/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

search/templates/search/search.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h3 class="head">Search pharmacies</h3></legend>
    {{form|crispy}}
  </fieldset>
  <input type="submit" value="search" />
</form>
{%if result%}
<h3 class="head">Pharmacy Details</h3>
<div class="grid_">
  <div>S.No</div>
  <div>Name</div>
  <div>Medicine Price(per unit in Rs)</div>
  <div>Pharmacy Phone Number</div>
  <div>Address</div>
  <div>Distane</div>
  <div>Direction</div>
  <div>Request Order</div>
  {%for pharma in result %}
      <div>{{forloop.counter}}</div>
      <div>{{pharma.name}}</div>
      <div>{{pharma.price}}</div>
      <div>{{pharma.ph}}</div>
      <div>{{pharma.address}}</div>
      <div>{{pharma.distance}}</div>
      <div>
        <form action="{%url 'map:direction'%}" method="post">
          {% csrf_token %}
          {{pharma.coord}}
          <input type="submit" value="Direction"/>
        </form>
      </div>
      <div>
        <a href="{% url 'users:request_order' medicine_name pharma.email pharma.name %}">Request Order</a>
      </div>
 
    {%endfor%}
</div>
<!--
<table>
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>medicine price</th>
      <th>ph no</th>
      <th>address</th>
      <th>distane</th>
      <th>direction</th>
      <th>request order</th>
    </tr>
  </thead>
  <tbody>
    {%for pharma in result %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{pharma.name}}</td>
      <td>{{pharma.price}}</td>
      <td>{{pharma.ph}}</td>
      <td>{{pharma.address}}</td>
      <td>{{pharma.distance}}</td>
      <td>
        <form action="{%url 'map:direction'%}" method="post">
          {% csrf_token %}
          {{pharma.coord}}
          <input type="submit" value="direction"/>
        </form>
      </td>
      <td><a href="{% url 'users:request_order' medicine_name pharma.email pharma.name %}">request order</a></td>
    </tr>

    {%endfor%}
  </tbody>
</table>-->
{% endif%} 
{%endblock content%}
<!--{{med_name}}/{{pharma.email}}-->