map/urls.py
from django.urls import path
from . import views
app_name = "map"

urlpatterns=[
    path('direction/',views.direction,name='direction'),
]

meds_nearby/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from search import views as search_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('',search_views.get_coord_api,name='get_coord'),
    path('map/',include('map.urls')),
    path('user/',include('users.urls')),

    #path('login/',auth_views.LoginView.as_view(template_name='user_registration/login.html'),name='login'),
    #path('logout/',auth_views.LogoutView.as_view(template_name='user_registration/logout.html'),name='logout')'''
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = "users"
urlpatterns=[
    path('register/',views.register,name='register'),
    path('profile/',views.profile_pg,name='profile'),
    path('login/',views.custom_login,name='login'),
    path('logout/',views.custom_logout,name='logout'),
    path('edit-profile/',views.edit_profile,name='edit'),
    path('request_order/<str:med_name>/<str:pharma_email>/<str:pharma_name>/',views.request_order,name='request_order'),
    path('activate/<uidb64>/<token>',views.activate, name='activate'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.
class PersonalDetails(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    age=models.IntegerField(default=18,)
    B_GROUPS= [
    ("O+ve", "O+ve"),
    ("A+ve", "A+ve"),
    ("B+ve", "B+ve"),
    ("AB+ve", "AB+ve"),
    ("O-ve", "O-ve"),
    ("A-ve", "A-ve"),
    ("B-ve", "B-ve"),
    ("AB-ve", "AB-ve"),
    ]
    blood_group=models.CharField(max_length=6
                                 ,choices=B_GROUPS)
    address=models.TextField(null=True)
    phone_no=models.CharField(max_length=10,null=True)
    def __str__(self):
        return f'{ self.user.username } profile'

    '''def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        img=Image.open(self.profile_image.path)
        if img.height>200 or img.width > 200:
            output_size=(200,200)
            img.thumbnail(output_size)
            img.save(self.profile_image.path)'''

users/forms.py
from django import forms
from .models import PersonalDetails
from django.forms import ModelForm,HiddenInput,Textarea
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
class PresonalDetailsForm(ModelForm):
    class Meta:
        model=PersonalDetails
        fields='__all__'#['age','blood_group']

class UserRegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=['username','email','password1','password2']
    def save(self,commit=False):
        user = super(UserRegistrationForm,self).save(commit=False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user #creates a new instance of the form and saves it to db
class UserUpdateForm(ModelForm):
    class Meta:
        model=User
        fields=['username', 'email' ]
class ProfileUpdateForm(ModelForm):
    class Meta:
        model=PersonalDetails
        fields=['age','blood_group']

class UserLoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super(UserLoginForm,self).__init__(*args,**kwargs)
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
class OrderForm(forms.Form):
    pharma_name=forms.CharField(label='pharmacy')
    medicine_name=forms.CharField()
    quantity=forms.IntegerField()
    delivery_address=forms.CharField(widget=Textarea)
    phone_no=forms.CharField(label='phone number')
    image=forms.ImageField(label='upload the prescription',required=True)
    pharma_email=forms.EmailField(widget=HiddenInput)

users/views.py
import os
from django.conf import settings 
from .handler import handle_uploaded_file
from PIL import Image
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import PresonalDetailsForm,UserRegistrationForm,UserUpdateForm,ProfileUpdateForm,UserLoginForm,OrderForm
from django.contrib.auth.models import User
from django.contrib import messages
from .models import PersonalDetails
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate, get_user_model
# Create your views here.
from .decorators import user_not_authenticated
from django.contrib.auth.forms import AuthenticationForm
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from .tokens import account_activation_token

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        print(uid,user)
    except:
        user = None
    print('in activate',user, account_activation_token.check_token(user, token))
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you are logged in")
        login(request,user)
        return redirect('get_coord')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('get_coord')
'''
'''
def activate_email(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("users/template_activate_account.html", 
        {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')
@user_not_authenticated
def register(request):# have to add try block if user alredy exists!!!!!
    if request.method=='POST':
        k=list(request.POST.keys())
        v=list(request.POST.values())
        di=dict(zip(k[1:5],v[1:5]))
        user_form=UserRegistrationForm(di)
        print("new",user_form.is_valid())
        print(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.is_active=False
            new_user.save()
            d2=dict()
            usn=user_form.cleaned_data.get('username')
            id=User.objects.get(username=usn).id
            print('id',type(id),id)
            d2['user']=str(id)
            d2.update(zip(k[5:],v[5:]))
            print(d2)
            detail_form=PresonalDetailsForm(d2)
            print("d2frm",detail_form.is_valid())
            if detail_form.is_valid():
                try:
                    detail_form.save()
                    activate_email(request,new_user,user_form.cleaned_data.get('email'))
                except Exception as err:
                    print(err)
                    new_user.delete()
                    for error in list(detail_form.errors.values()):
                        messages.error(request, error)
                else:
                    messages.success(request,'user acc created for {}'.format(usn))
                    new_user=User.objects.get(username=usn)
                    login(request,new_user)
                    return redirect('get_coord')
            else:
                new_user.delete()
        else:
            for error in list(user_form.errors.values()):
                messages.error(request, error)
            detail_form=PresonalDetailsForm()
            

    else:
        user_form=UserRegistrationForm()
        detail_form=PresonalDetailsForm()
    content={'user_form':user_form,'details':detail_form}
    return render(request,'users/register.html',content)
@login_required
def profile_pg(request):
    return render(request,'users/profile.html')
@user_not_authenticated
def custom_login(request):
    if request.method == 'POST':
        form=UserLoginForm(request=request,data=request.POST)
        if form.is_valid():
            user=authenticate(username=form.cleaned_data['username'],
                          password=form.cleaned_data['password'])
            if user is not None:
                login(request,user)
                messages.success(request,f"Hello {user.username}")
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect('get_coord')
                ''''''
        else:
            for error in list(form.errors.values()):
                messages.error(request,error)
    form=UserLoginForm()
    return render(request,'users/login.html',{'form':form})
@login_required
def custom_logout(request):
    logout(request)
    #messages.info(request,'logged out sucessfully')
    return render(request,'users/logout.html')
@login_required
def edit_profile(request):
    if request.method == 'POST':
        u_form=UserUpdateForm(request.POST,instance=request.user)
        p_form=ProfileUpdateForm(request.POST,instance=request.user.personaldetails)
        print(request.POST,u_form.is_valid(), p_form.is_valid())
        print(request.FILES)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,'sucessesfully updated your profile')
            return redirect('users:profile')
    else:
        u_form=UserUpdateForm(instance=request.user)
        p_form=ProfileUpdateForm(instance=request.user.personaldetails)
    return render(request,'users/edit_profile.html',{'u_form':u_form,'p_form':p_form})

def send_user_email(request,form):
    subject='Request to place order made'
    message=render_to_string("users/email_to_user.html", 
        {'med_name':form.cleaned_data['medicine_name'],
         'user':request.user,
         'pharmacy_name':form.cleaned_data['pharma_name']
        })
    recipent_list=[request.user.email]
    email=EmailMessage(subject,message,to=recipent_list )
    email.send()
def send_email_with_attachment(request,path,form):
    subject='Request to order medicine'
    message=render_to_string("users/order_req.html", 
        {'med_name':form.cleaned_data['medicine_name'],
         'user':request.user,
         'quantity':form.cleaned_data['quantity'],
         'address':form.cleaned_data['delivery_address'],
         'phone_no':form.cleaned_data['phone_no'],
         'email':request.user.email,
        })
    recipent_list=[form.cleaned_data['pharma_email']]
    email = EmailMessage(subject,message,to=recipent_list )
    email.attach_file(f"{settings.BASE_DIR}/media/prescription/{path}")
    if email.send():
        pharma_name=form.cleaned_data['pharma_name']
        messages.success(request,f'Your request for order has been made to {pharma_name}')
    else:
        messages.error(request,'there was some error in placing the request for order')
    os.remove(f"{settings.BASE_DIR}/media/prescription/{path}")
@login_required
def request_order(request,**args):
    print(request.GET,args)
    user=request.user
    personal_detail=PersonalDetails.objects.get(user=user)
    address=personal_detail.address
    phone_no=personal_detail.phone_no
    value_={
    'pharma_name':args['pharma_name'],
    'medicine_name':args['med_name'],
    'quantity':0,
    'delivery_address':address,
    'phone_no':phone_no,
    'image':None,
    'pharma_email':args['pharma_email']}
    form=OrderForm(value_)
    print(form)
    print(form.is_valid())
    if request.method=='POST':
        form=OrderForm(request.POST,request.FILES)
        print(form.is_valid())
        if form.is_valid():
            path=handle_uploaded_file(request.FILES['image'])
            print(path,request.user.email)
            send_email_with_attachment(request,path,form)
            send_user_email(request,form)
        return redirect('get_coord')

    return render(request,'users/order_form.html',{'form':form})

# Create your views here.

users/templates/users/edit_profile.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <legend>Edit Profile</legend>
        {{u_form|crispy}}
        <h2>Details</h2>
        <p>{{p_form.age|as_crispy_field}}</p>
        <p>{{p_form.blood_group|as_crispy_field}}</p>
    </fieldset>
    <input type="submit" value="save">
</form>
<div style="padding-top: 2rem;">
    <small>
    <a href="{%url 'users:profile'%}">Cancel</a>
    </small>
</div>
{%endblock content%}

users/templates/users/email_to_user.html
{% autoescape off %}
Hi {{user.username}},

    Your order to buy the medicine {{med_name}} has been requested to {{pharmacy_name}}.
You will be notified by the pharmacy regarding the confirmation of the order.

With regards,
MedsNearby
{% endautoescape %}

users/templates/users/image_render.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<h1>{{form|crispy}}</h1>
<img src="/media/prescription/{{form}}" alt="">

{%endblock content%}

users/templates/users/login.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<div class="form_">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Login</legend>
            {{form|crispy}}
        </fieldset>
        <input type="submit" value="login">
    </form>

    <div class="btm">
        <div>
            <small>
                Need an Account? <a href="{%url 'users:register'%}">Sign Up</a>
                <br>
                <a href="{%url 'password_reset' %}">forgot password?</a>
             </small>
        </div>
        
    </div>
</div>
{%endblock content%}

users/templates/users/logout.html
{%extends 'search/base.html' %}
{% block content%}
<h2 class="head">you have been logged out</h2>
<div class="btm">
    <div>
        <small>
            <a href="{%url 'users:login'%}">login again</a>
        </small>
    </div>
    
</div>
{%endblock content%}

users/templates/users/order_form.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <legend><h3 class="head">Order</h3></legend>
        <div class="form__">{{form|crispy}}</div>
    </fieldset>
    <input type="submit" value="submit">
</form>

{%endblock content%}

users/templates/users/order_req.html
{% autoescape off %}
This mail is to request an order for the medicine {{med_name}}.
The order detail:
medicine:{{med_name}}
quantity:{{quantity}}

The customer detail:
Name: {{user.username}}
Address:{{address}}
Phone Number:{{phone_no}}
email_id : {{email}}

An image containing the prescription is attached.
please do verify the placement of order by sending an email to the customer with payment details.

With regards,
MedsNearby
{% endautoescape %}

users/templates/users/password_reset.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3 class="head">reset password</h3></legend>
        {{form|crispy}}
    </fieldset>
    <input type="submit" value="request password reset">
</form>

{%endblock content%}

users/templates/users/password_reset_complete.html
{%extends 'search/base.html' %}
{% block content%}
<h4 class="pass">
    your password has been rest sucessfully
</h4>
<div class='btm'>
<div>
    <small>
        <a href="{%url 'users:login'%}">Sign In Here</a>
    </small>
</div>
</div>

{%endblock content%}

users/templates/users/password_reset_confirm.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3 class="head">Reset password</h3></legend>
        {{form|crispy}}
    </fieldset>
    <input type="submit" value="reset password ">
</form>

{%endblock content%}

users/templates/users/password_reset_done.html
{%extends 'search/base.html' %}
{% block content%}
<h4 class="pass">an email has been sent with instructions to reset your password</h4>
{%endblock content%}

users/templates/users/profile.html
{%extends 'search/base.html' %}
{% block content%}
<div class="form_">
    <legend><h3 class="head">User profile</h3></legend>
    <p>Name:{{user.username}}</p>
    <p>Email:{{user.email}}</p>
    <p>Blood Group:{{user.personaldetails.blood_group}}</p>
    <p>Age:{{user.personaldetails.age}}</p>
    <p>Phone number:{{user.personaldetails.phone_no}}</p>
    <p>Address:{{user.personaldetails.address}}</p>
</div>

<div class='btm'>
    <div>
        <a href="{% url 'users:edit' %}">Edit Profile</a>
    </div>
    <div>
        <a href="{%url 'password_reset' %}">Change Password</a>
    </div>
</div>
{%endblock content%}

users/templates/users/register.html
{%extends 'search/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3 class="head">join today!</h3></legend>
        {{user_form|crispy}}
        <h2>Details</h2>
        {{details.age|as_crispy_field}}
        {{details.blood_group|as_crispy_field}}
        {{details.address|as_crispy_field}}
        {{details.phone_no|as_crispy_field}}
    </fieldset>
    <input type="submit" value="submit">
</form>
<div class="btm">
    <div>
        <small>
            Have an Account? <a href="{%url 'users:login'%}">Sign In</a>
        </small>
    </div>
    
</div>
{%endblock content%}

users/templates/users/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}